/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WifiSettingsRouteImport } from './routes/wifi-settings'
import { Route as IndexRouteImport } from './routes/index'

const WifiSettingsRoute = WifiSettingsRouteImport.update({
  id: '/wifi-settings',
  path: '/wifi-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wifi-settings': typeof WifiSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wifi-settings': typeof WifiSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wifi-settings': typeof WifiSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wifi-settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wifi-settings'
  id: '__root__' | '/' | '/wifi-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WifiSettingsRoute: typeof WifiSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wifi-settings': {
      id: '/wifi-settings'
      path: '/wifi-settings'
      fullPath: '/wifi-settings'
      preLoaderRoute: typeof WifiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WifiSettingsRoute: WifiSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
